# Generated by Django 4.0.4 on 2022-04-12 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('e_name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('e_desc', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.SmallIntegerField(choices=[(0, 'solo'), (1, 'team')], verbose_name='Type')),
                ('co_ord', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Co-ordinators')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
