# Generated by Django 4.0.4 on 2022-04-12 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestants',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('gender', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], max_length=20, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('MEC', 'FEMALE'), ('ECE', 'OTHERS'), ('CHE', 'OTHERS'), ('EE', 'OTHERS'), ('CIV', 'OTHERS')], max_length=244)),
                ('year', models.SmallIntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('event', models.ManyToManyField(to='events.events')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('t_name', models.CharField(max_length=244)),
                ('contestants', models.ManyToManyField(to='contestants.contestants')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
