# Generated by Django 4.0.4 on 2022-04-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_co_ord'),
        ('contestants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestants',
            name='event',
            field=models.ManyToManyField(blank=True, to='events.events'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='contestants',
            field=models.ManyToManyField(blank=True, to='contestants.contestants'),
        ),
    ]
