# Generated by Django 3.1.7 on 2021-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('icmr', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('contact_1', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('patient_status', models.CharField(choices=[('A', 'Active'), ('R', 'Recovered'), ('M', 'Migrated')], default='A', max_length=40)),
                ('covid_facility', models.TextField(blank=True, default='G.T.R Base Hospital, Almora', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
