# Generated by Django 3.1.7 on 2021-05-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patientprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='aadhar_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='contact_1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
